# Generated by Django 4.1.4 on 2023-02-04 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Djangoforms', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='year_in_school',
            field=models.CharField(choices=[(None, '---------'), ('FR', 'Freshman'), ('SO', 'Sophomore'), ('GR', 'Graduate'), ('JR', 'Junior'), ('SR', 'Senior')], max_length=2),
        ),
    ]
